<?php

use App\Models\Bot;
use App\Models\BotRoute;
use App\Models\User;
use App\Services\SchemaValidator;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('passes when bot has routes and valid config', function () {
    $admin = User::factory()->admin()->create();
    $bot = Bot::factory()->for($admin, 'creator')->create([
        'messenger_config' => ['telegram'],
    ]);
    BotRoute::factory()->for($bot)->create();

    $validator = new SchemaValidator($bot);
    $result = $validator->validate();

    expect($result->isValid())->toBeTrue();
});

test('fails when bot has no routes', function () {
    $admin = User::factory()->admin()->create();
    $bot = Bot::factory()->for($admin, 'creator')->create([
        'messenger_config' => ['telegram'],
    ]);

    $validator = new SchemaValidator($bot);
    $result = $validator->validate();

    expect($result->isValid())->toBeFalse();
    expect($result->errors)->toContain('Бот должен иметь хотя бы один маршрут');
});

test('fails when messenger config is empty', function () {
    $admin = User::factory()->admin()->create();
    $bot = Bot::factory()->for($admin, 'creator')->create([
        'messenger_config' => [],
    ]);
    BotRoute::factory()->for($bot)->create();

    $validator = new SchemaValidator($bot);
    $result = $validator->validate();

    expect($result->isValid())->toBeFalse();
    expect($result->errors)->toContain('Необходимо настроить хотя бы один мессенджер');
});

test('fails when flow has no steps', function () {
    $admin = User::factory()->admin()->create();
    $bot = Bot::factory()->for($admin, 'creator')->create([
        'messenger_config' => ['telegram'],
    ]);
    BotRoute::factory()->for($bot)->create();
    $bot->flows()->create([
        'name' => 'EmptyFlow',
        'graph' => ['nodes' => [], 'edges' => []],
    ]);

    $validator = new SchemaValidator($bot);
    $result = $validator->validate();

    expect($result->isValid())->toBeFalse();
    expect($result->errors[0])->toContain('EmptyFlow');
});

test('fails when flow has no on_complete node', function () {
    $admin = User::factory()->admin()->create();
    $bot = Bot::factory()->for($admin, 'creator')->create([
        'messenger_config' => ['telegram'],
    ]);
    BotRoute::factory()->for($bot)->create();
    $bot->flows()->create([
        'name' => 'NoComplete',
        'graph' => [
            'nodes' => [
                ['id' => 's1', 'type' => 'ask_text', 'data' => ['text' => 'Hi'], 'position' => ['x' => 0, 'y' => 0]],
            ],
            'edges' => [],
        ],
    ]);

    $validator = new SchemaValidator($bot);
    $result = $validator->validate();

    expect($result->isValid())->toBeFalse();
    expect($result->errors[0])->toContain('on_complete');
});

test('fails when flow has duplicate explicit stepName', function () {
    $admin = User::factory()->admin()->create();
    $bot = Bot::factory()->for($admin, 'creator')->create([
        'messenger_config' => ['telegram'],
    ]);
    BotRoute::factory()->for($bot)->create();
    $bot->flows()->create([
        'name' => 'DupFlow',
        'graph' => [
            'nodes' => [
                ['id' => 'start', 'type' => 'start', 'data' => [], 'position' => ['x' => 0, 'y' => 0]],
                ['id' => 'a', 'type' => 'ask_text', 'data' => ['text' => 'Q1', 'stepName' => 'askThing'], 'position' => ['x' => 0, 'y' => 0]],
                ['id' => 'b', 'type' => 'ask_text', 'data' => ['text' => 'Q2', 'stepName' => 'askThing'], 'position' => ['x' => 0, 'y' => 0]],
                ['id' => 'end', 'type' => 'on_complete', 'data' => [], 'position' => ['x' => 0, 'y' => 0]],
            ],
            'edges' => [
                ['source' => 'start', 'target' => 'a'],
                ['source' => 'a', 'target' => 'b'],
                ['source' => 'b', 'target' => 'end'],
            ],
        ],
    ]);

    $validator = new SchemaValidator($bot);
    $result = $validator->validate();

    expect($result->isValid())->toBeFalse();
    expect(implode("\n", $result->errors))->toContain('askThing');
});

test('fails when autogenerated stepName collides', function () {
    $admin = User::factory()->admin()->create();
    $bot = Bot::factory()->for($admin, 'creator')->create([
        'messenger_config' => ['telegram'],
    ]);
    BotRoute::factory()->for($bot)->create();
    $bot->flows()->create([
        'name' => 'AutoDupFlow',
        'graph' => [
            'nodes' => [
                ['id' => 'start', 'type' => 'start', 'data' => [], 'position' => ['x' => 0, 'y' => 0]],
                // Оба текста дадут autogen "askGender"
                ['id' => 'a', 'type' => 'ask_text', 'data' => ['text' => 'Gender'], 'position' => ['x' => 0, 'y' => 0]],
                ['id' => 'b', 'type' => 'ask_text', 'data' => ['text' => 'Gender'], 'position' => ['x' => 0, 'y' => 0]],
                ['id' => 'end', 'type' => 'on_complete', 'data' => [], 'position' => ['x' => 0, 'y' => 0]],
            ],
            'edges' => [
                ['source' => 'start', 'target' => 'a'],
                ['source' => 'a', 'target' => 'b'],
                ['source' => 'b', 'target' => 'end'],
            ],
        ],
    ]);

    $validator = new SchemaValidator($bot);
    $result = $validator->validate();

    expect($result->isValid())->toBeFalse();
    expect(implode("\n", $result->errors))->toContain('askGender');
});

test('passes with unique stepNames', function () {
    $admin = User::factory()->admin()->create();
    $bot = Bot::factory()->for($admin, 'creator')->create([
        'messenger_config' => ['telegram'],
    ]);
    BotRoute::factory()->for($bot)->create();
    $bot->flows()->create([
        'name' => 'OkFlow',
        'graph' => [
            'nodes' => [
                ['id' => 'start', 'type' => 'start', 'data' => [], 'position' => ['x' => 0, 'y' => 0]],
                ['id' => 'a', 'type' => 'ask_text', 'data' => ['text' => 'Name'], 'position' => ['x' => 0, 'y' => 0]],
                ['id' => 'b', 'type' => 'ask_text', 'data' => ['text' => 'Age'], 'position' => ['x' => 0, 'y' => 0]],
                ['id' => 'end', 'type' => 'on_complete', 'data' => [], 'position' => ['x' => 0, 'y' => 0]],
            ],
            'edges' => [
                ['source' => 'start', 'target' => 'a'],
                ['source' => 'a', 'target' => 'b'],
                ['source' => 'b', 'target' => 'end'],
            ],
        ],
    ]);

    $validator = new SchemaValidator($bot);
    $result = $validator->validate();

    expect($result->isValid())->toBeTrue();
});

test('устаревший плоский формат кнопок в ноде flow даёт ошибку', function () {
    $admin = User::factory()->admin()->create();
    $bot = Bot::factory()->for($admin, 'creator')->create([
        'messenger_config' => ['telegram'],
    ]);
    BotRoute::factory()->for($bot)->create();
    $bot->flows()->create([
        'name' => 'Main',
        'graph' => [
            'nodes' => [
                ['id' => 'start', 'type' => 'start', 'data' => [], 'position' => ['x' => 0, 'y' => 0]],
                ['id' => 'ask', 'type' => 'ask_keyboard', 'data' => [
                    'text' => 'Привет',
                    'buttons' => [
                        ['label' => 'A', 'action' => 'a'],
                        ['label' => 'B', 'action' => 'b'],
                    ],
                ], 'position' => ['x' => 0, 'y' => 0]],
                ['id' => 'done', 'type' => 'on_complete', 'data' => [], 'position' => ['x' => 0, 'y' => 0]],
            ],
            'edges' => [
                ['source' => 'start', 'target' => 'ask'],
                ['source' => 'ask', 'target' => 'done'],
            ],
        ],
    ]);

    $validator = new SchemaValidator($bot);
    $result = $validator->validate();

    expect($result->isValid())->toBeFalse();
    expect(implode("\n", $result->errors))->toContain('Клавиатура в ноде «ask» flow «Main» в устаревшем формате');
});

test('новый матричный формат кнопок в ноде flow проходит валидацию', function () {
    $admin = User::factory()->admin()->create();
    $bot = Bot::factory()->for($admin, 'creator')->create([
        'messenger_config' => ['telegram'],
    ]);
    BotRoute::factory()->for($bot)->create();
    $bot->flows()->create([
        'name' => 'Main',
        'graph' => [
            'nodes' => [
                ['id' => 'start', 'type' => 'start', 'data' => [], 'position' => ['x' => 0, 'y' => 0]],
                ['id' => 'ask', 'type' => 'ask_keyboard', 'data' => [
                    'text' => 'Привет',
                    'buttons' => [
                        [['type' => 'action', 'label' => 'A', 'action' => 'a']],
                    ],
                ], 'position' => ['x' => 0, 'y' => 0]],
                ['id' => 'done', 'type' => 'on_complete', 'data' => [], 'position' => ['x' => 0, 'y' => 0]],
            ],
            'edges' => [
                ['source' => 'start', 'target' => 'ask'],
                ['source' => 'ask', 'target' => 'done'],
            ],
        ],
    ]);

    $validator = new SchemaValidator($bot);
    $result = $validator->validate();

    expect($result->isValid())->toBeTrue();
});

test('устаревший плоский формат кнопок в блоке маршрута даёт ошибку', function () {
    $admin = User::factory()->admin()->create();
    $bot = Bot::factory()->for($admin, 'creator')->create([
        'messenger_config' => ['telegram'],
    ]);
    BotRoute::factory()->for($bot)->create([
        'match' => '/menu',
        'handler_schema' => [
            'blocks' => [
                ['type' => 'reply_keyboard', 'params' => [
                    'text' => 'Меню',
                    'buttons' => [
                        ['label' => 'A', 'action' => 'a'],
                    ],
                ]],
            ],
        ],
    ]);

    $validator = new SchemaValidator($bot);
    $result = $validator->validate();

    expect($result->isValid())->toBeFalse();
    expect(implode("\n", $result->errors))->toContain('Клавиатура в блоке #1 маршрута «/menu» в устаревшем формате');
});
